[custom]
;不要随意改变关键字，否则会导致出错

;自动测速：支持
;GPT_Web：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持
;去广告：自选，容易误杀
;显示IP归属地应用伪装：自选 (去掉对应的规则标志位、分组标志位前的分号即可)

;设置规则标志位
ruleset=🤖 AI服务,https://raw.githubusercontent.com/cutethotw/ClashRule/refs/heads/main/Rule/Claude.list
ruleset=🤖 AI服务,clash-classic:https://ddgksf2013.top/filter/Ai.yaml
ruleset=🤖 AI服务,https://raw.githubusercontent.com/Wym1ng/Ruleset/main/Rule/AI_Others.list
ruleset=🕹️ Adobe,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Adobe/Adobe.list
ruleset=🚀 起飞,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🚀 起飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🚀 起飞,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🚀 起飞,https://raw.githubusercontent.com/Wym1ng/Ruleset/main/Rule/ProxyLite.list
ruleset=🕹 IP归属地伪装,clash-classic:https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🎶 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📢 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=🖥 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🌍 外洋媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
;ruleset=🐼 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=⏩ 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=⏩ 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ Microsoft服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Ⓜ️ Microsoft服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍎 Apple服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🚀 起飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=⏩ 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=⏩ 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=⏩ 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=⏩ 直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

;设置分组标志位
custom_proxy_group=🚀 起飞`select`[]🇭🇰 香港HK`[]👉🏻 指定线路`[]🔯 故障切换`[]🚁 专线`[]🇸🇬 狮城SG`[]🇯🇵 日本JP`[]🇨🇳 台湾TW`[]🇺🇲 美国US
custom_proxy_group=👉🏻 指定线路`select`.*
custom_proxy_group=🚁 专线`select`(IEPL|IPLC|三线|专线)
custom_proxy_group=🔯 故障切换`fallback`^(?=.*家宽).*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🔰 备用线路`select`.*
custom_proxy_group=🤖 AI服务`select`[]🇺🇲 美国US`[]🇸🇬 狮城SG`[]🔯 故障切换`[]🚁 专线`[]🇯🇵 日本JP`[]👉🏻 指定线路`(美国|US|新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🕹️ Adobe`select`[]REJECT`[]DIRECT`[]🚀 起飞
custom_proxy_group=🎶 TikTok`select`[]DIRECT`[]🇸🇬 狮城SG`[]🇯🇵 日本JP`[]🇺🇲 美国US`[]👉🏻 指定线路`(新加坡|坡|狮城|SG|Singapore|马来西亚|MY|菲|泰|越南)
custom_proxy_group=📲 Telegram`select`[]🇭🇰 香港HK`[]🚀 起飞`[]👉🏻 指定线路`[]🇸🇬 狮城SG
custom_proxy_group=🖥 YouTube`select`[]🚀 起飞`[]👉🏻 指定线路`[]🇭🇰 香港HK`[]🇸🇬 狮城SG`[]🇺🇲 美国US`[]🇯🇵 日本JP`(蒙古|MN)`(澳门|MO)`(RU)`(尼泊尔|NP)`(阿塞拜疆)`(孟加拉|BD)`(约旦|JO)`(柬埔寨|KH)`(土耳其|TR|Turkey)
custom_proxy_group=🌍 外洋媒体`select`[]🚀 起飞`[]🇭🇰 香港HK`[]🇯🇵 日本JP`[]🇺🇲 美国US
;custom_proxy_group=🐼 国内媒体`select`[]DIRECT`[]🚀 起飞`[]👉🏻 指定线路`[]🇭🇰 香港HK`[]🇸🇬 狮城SG`[]🇯🇵 日本JP`[]🇺🇲 美国US
custom_proxy_group=📢 Google`select`[]🚀 起飞`[]🔯 故障切换`[]🇸🇬 狮城SG`[]🇺🇲 美国US`[]🇯🇵 日本JP`[]🇭🇰 香港HK
custom_proxy_group=🍎 Apple服务`select`[]DIRECT`[]👉🏻 指定线路`[]🇭🇰 香港HK`[]🇸🇬 狮城SG`[]🇯🇵 日本JP`[]🇺🇲 美国US
custom_proxy_group=Ⓜ️ Microsoft服务`select`[]DIRECT`[]🚀 起飞`[]🇭🇰 香港HK`[]🇸🇬 狮城SG`[]🇯🇵 日本JP`[]🇺🇲 美国US
custom_proxy_group=🕹 IP归属地伪装`select`[]DIRECT`[]👉🏻 指定线路`[]🇭🇰 香港HK`[]🇸🇬 狮城SG`[]🇯🇵 日本JP`[]🇺🇲 美国US
custom_proxy_group=⏩ 直连`select`[]DIRECT`[]👉🏻 指定线路
;custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 起飞`[]🇭🇰 香港HK`[]🇸🇬 狮城SG`[]🇯🇵 日本JP`[]🇺🇲 美国US`[]DIRECT
custom_proxy_group=🇭🇰 香港HK`url-test`^(?!.*(IEPL|IPLC)).*(港|HK|Hong Kong).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本JP`url-test`^(?!.*(IEPL|IPLC)).*(日本|川日|东京|大阪|霓虹|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国US`url-test`^(?!.*(IEPL|IPLC)).*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|洛|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|USA).*`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇸🇬 狮城SG`url-test`^(?!.*(IEPL|IPLC)).*(新加坡|坡|狮城|淡马|SG|Singapore).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾TW`url-test`^(?!.*(IEPL|IPLC)).*(台|新北|彰化|澎湖|TW|Taiwan).*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🇰🇷 韩国KR`url-test`^(?!.*(IEPL|IPLC)).*(KR|Korea|KOR|首尔|南傀|韩|韓).*`http://www.gstatic.com/generate_204`300,,50

;设置分组标志位
enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://github.com/cutethotw/ClashRule/blob/main/GeneralClashRule.ini
